apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: hello-task
spec:
  steps:
    - name: echo
      image: ubuntu
      envFrom:
       - configMapRef:
           name: environment-properties
      command: ["/bin/bash", "-c"]
      args:
        - echo -e "The environment for this Step is ";
          env
      
        
