apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: hello-task
spec:
  steps:
    - name: trigger-payload
      image: ubuntu
       env:
        - name: TRIGGER_PAYLOAD
      envFrom:
       - configMapRef:
           name: trigger
           key: payload.json
      command: ["/bin/bash", "-c"]
      args:
        - echo -e "The \033[36menvironment\033[0m for this Step is ";
          env;
          echo "";
          echo "One sample property from this environment is >>";
          echo $TRIGGER_PAYLOAD

