apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: hello-trigger-template
spec:
  params:
    - name: event-payload
      description: event payload from the trigger webhook
      default: ''
    - name: body
      description: body of msg
      default: testing default body
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: hello-pipeline
    - apiVersion: tekton.dev/v1alpha1
      kind: ConfigMap
      metadata:
        name: trigger
        data:
          payload.json: $(params.event-payload)
    - apiVersion: tekton.dev/v1alpha1
      kind: TaskRun
      metadata:
        generateName: task-run-
      spec:
        taskSpec:
          steps:
            - image: ubuntu
              script: |
                #! /bin/bash
                echo $(params.body)

