apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: hello-trigger-template
spec:
  params:
    - name: event-payload
      description: event payload from the trigger webhook
      default: ''
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: hello-pipeline
    - apiVersion: tekton.dev/v1alpha1
        kind: ConfigMap
        metadata:
          name: trigger
        data:
          payload.json: $(params.event-payload)

